kind: CronJob
apiVersion: batch/v1
metadata:
  name: minute-backup
  namespace: nginx
spec:
  schedule: "*/2 * * * *"
  jobTemplate:
    spec:
      template:  
        metadata:
          name: minut-backup
          labels:
           app: minute-backup
        spec:
         containers:
         - name: backup-container
           image: busybox
           command:
           - sh
           - -c
           - >
             echo "backup started";
             mkdir -p /backup &&
             mkdir -p /demo-data &&
             cp -r /demo/data /backup &&
             echo "backup completed";
           volumeMounts:
           - name: data-volume
             mountPath: /demo-data
           - name: backup-volume
             mountPath: /backup
         restartPolicy: OnFailure
         volumes:
            - name: data-volume
              hostPath: 
                 path: /demo-data
                 type: DirectoryOrCreate      
            - name: backup-volume
              hostPath: 
                 path: /backup
                 type: DirectoryOrCreate      
