kind: Job
apiVersion: batch/v1
metadata:
  name: nginx-job
  namespace: nginx
spec:
  completions: 1
  parallelism: 1
  template:
    metadata:
      name: demo-job-pod
      labels:
        app: batch-task
    spec:
     containers:
      - name: batch-cont
        image: busybox
        command: ["sh","-c","echo hello world && sleep 10"]
     restartPolicy: Never     
