kind: Pod
apiVersion: v1
metadata:
  name: nginx
  namespace: nginx
spec:
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 80
  tolerations:
    - key: "prod"
      value: "true"
      operator: "Equal"
      effect: "NoSchedule"  
           
