kind: Pod
apiVersion: v1
metadata:
  name: sidecar-test
spec:
  volumes:
    - name: shared-log
      emptyDir: {}
  containers:
    - name: main-container
      image: busybox:latest
      command: ["sh","-c","while true; do echo 'hi' >> /var/log/app.log; sleep 5;done"]
      volumeMounts:
        - name: shared-log
          mountPath: /var/log/

    - name: sidecar-container
      image: busybox:latest
      command: ["sh","-c","tail -f /var/log/app.log"]  
      volumeMounts:
        - name: shared-log
          mountPath: /var/log/
